thymio-01:
  option_centers: [40, 601, 84]
  allowed_offsets: [15, 25, 15]

thymio-03:
  option_centers: [41, 548, 80]
  allowed_offsets: [15, 10, 15]

thymio-04:
  option_centers: [35, 592, 82]
  allowed_offsets: [15, 10, 20]

thymio-05:
  option_centers: [35, 496, 74]
  allowed_offsets: [15, 10, 15]

thymio-06:
  option_centers: [54, 772, 118]
  allowed_offsets: [15, 15, 20]

thymio-07:
  option_centers: [41, 615, 87]
  allowed_offsets: [15, 45, 20]

thymio-08:
  option_centers: [37, 569, 77]
  allowed_offsets: [15, 40, 15]

thymio-09:
  option_centers: [44, 596, 97]
  allowed_offsets: [20, 10, 30]

thymio-10:
  option_centers: [33, 527, 76]
  allowed_offsets: [15, 10, 15]

thymio-11:
  option_centers: [41, 649, 92]
  allowed_offsets: [15, 10, 20]

thymio-12:
  option_centers: [50, 640, 101]
  allowed_offsets: [15, 20, 15]

thymio-13:
  option_centers: [31, 584, 73]
  allowed_offsets: [15, 25, 15]

thymio-14:
  option_centers: [50, 752, 110]
  allowed_offsets: [15, 10, 15]

thymio-15:
  option_centers: [42, 698, 93]
  allowed_offsets: [15, 35, 15]

thymio-16:
  option_centers: [41, 651, 89]
  allowed_offsets: [15, 40, 15]

thymio-17:
  option_centers: [45, 653, 99]
  allowed_offsets: [15, 15, 15]

thymio-18:
  option_centers: [36, 590, 82]
  allowed_offsets: [15, 20, 15]

thymio-19:
  option_centers: [41, 691, 89]
  allowed_offsets: [15, 15, 15]

thymio-20:
  option_centers: [44, 558, 87]
  allowed_offsets: [15, 15, 15]

thymio-21:
  option_centers: [42, 548, 83]
  allowed_offsets: [10, 10, 25]

thymio-25:
  option_centers: [55, 782, 115]
  allowed_offsets: [20, 15, 20]
